const $=id=>document.getElementById(id);let data=[],brokerRows=[],liveEnabled=false,selectedTickers=new Set();const BACKEND_URL=window.STOCKFLOW_BACKEND_URL||'https://stock-accumulation-pwa.maxsaveofficial.deno.net',PROVIDER_KEY='stockflow-provider',CACHE_KEY='stockflow-auto-cache-v1';
// ...
