const $=id=>document.getElementById(id);let data=makeDemo(),brokerRows=[],liveEnabled=false,selectedTickers=new Set();const BACKEND_URL=window.STOCKFLOW_BACKEND_URL||'https://stock-accumulation-pwa.maxsaveofficial.deno.net',PROVIDER_KEY='stockflow-provider',CACHE_KEY='stockflow-auto-cache-v1';
function makeDemo(){const ts=['BBCA','BBRI','BMRI','TLKM','ASII','BBNI','ICBP','INDF','ANTM','MDKA','GOTO','UNVR','PGAS','ADRO','PTBA','SMGR','JPFA','KLBF','AMRT','ACES'];return ts.map((ticker,k)=>{let p=1000+k*275,rows=[],reg=k<6?'BUY':k>=14?'SELL':'NEUTRAL';for(let i=0;i<140;i++){const d=new Date(Date.now()-(139-i)*86400000),c=Math.sin((i+k)*.37),n=Math.sin((i*7+k*11)*.91)*.004,dir=reg==='BUY'?.0028:reg==='SELL'?-.0028:.0001*c,o=p*(1+n),m=dir+(reg==='BUY'?Math.max(0,c)*.006:reg==='SELL'?-Math.max(0,c)*.006:c*.008)+n*.45,cl=o*(1+m),h=Math.max(o,cl)*(1+(reg==='BUY'?.01:.006)+Math.abs(n)),l=Math.min(o,cl)*(1+(reg==='SELL'?-.01:-.006)-Math.abs(n)),v=Math.round((650000+((i*9301+k*17011)%700000))*(reg==='NEUTRAL'?1:(i%9===0?1.8:1.05)));rows.push({date:d.toISOString().slice(0,10),ticker,open:o,high:h,low:l,close:cl,volume:v,value:v*cl,brokerNetValue:(reg==='BUY'?.16:reg==='SELL'?- .16:.02*c)*v*cl});p=cl}return{ticker,rows,lookback:20}})}
function esc(x){return String(x??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]||m))}
function fmt(x,d=2){return x==null||!Number.isFinite(Number(x))?'-':Number(x).toFixed(d)}
function statCells(s){return `<td>${s.count}</td><td>${fmt(s.hitRate,1)}%</td><td>${fmt(s.avgReturn)}%</td><td>${fmt(s.medianReturn)}%</td><td>${fmt(s.expectancy)}%</td><td>${fmt(s.winLossRatio)}</td><td>${fmt(s.avgMAE)}%</td><td>${fmt(s.avgMFE)}%</td>`}
function table(items,type){return items.length?items.map((x,i)=>`<tr data-ticker="${esc(x.ticker)}"><td>${i+1}</td><td><b>${esc(x.ticker)}</b></td><td>${x.score.toFixed(0)}</td><td>${(type==='BUY'?x.acc:x.dist).toFixed(0)}</td><td>${(type==='BUY'?x.trend:x.breakdown).toFixed(0)}</td></tr>`).join(''):'<tr><td colspan="5">Belum ada kandidat.</td></tr>'}
function render(){const lb=+$('lookback').value,h=20,chosen=[...selectedTickers],pool=chosen.length===data.length?data:data.filter(x=>chosen.includes(x.ticker)),s=chosen.length===1?chosen[0]:'ALL',o=StockFlow.classify(pool,h),r=o.results,n=r.length||1,b=r.filter(x=>x.signal==='BUY').length,sl=r.filter(x=>x.signal==='SELL').length;$('donutText').textContent=`${b} / ${r.length-b-sl} / ${sl}`;$('avgAccum').textContent=(r.reduce((a,x)=>a+x.acc,0)/n).toFixed(0);$('avgDistrib').textContent=(r.reduce((a,x)=>a+x.dist,0)/n).toFixed(0);$('avgVol').textContent=(r.reduce((a,x)=>a+x.volRatio,0)/n).toFixed(2)+'x';$('avgRisk').textContent=(r.reduce((a,x)=>a+x.breakdown,0)/n).toFixed(0);$('buyTable').innerHTML=table(o.buy,'BUY');$('sellTable').innerHTML=table(o.sell,'SELL');const results=StockFlowCalibration.multiHorizon(pool,[1,3,5,10,20],{lookback:Math.min(lb,20),costPct:1});const points=results.map(x=>`<div><small>T+${x.horizon}</small><b>${fmt(x.total.avgReturn,2)}%</b><span>${fmt(x.total.hitRate,1)}% hit · ${x.total.count} signal</span></div>`).join('');$('backtest').innerHTML=`<div class="btchart"><div class="btbars">${results.map(x=>`<div class="btpoint" style="--h:${Math.min(100,Math.max(4,50+Number(x.total.avgReturn||0)*8))}%"><i></i><small>T+${x.horizon}</small><b>${fmt(x.total.avgReturn,2)}%</b></div>`).join('')}</div><div class="btlegend"><span>Directional return net cost</span><em>Assumption internal: round-trip cost 1.00%</em></div><div class="btstats">${points}</div></div>`;bindRows();if(s!=='ALL')detail(s);else $('detail').innerHTML='Klik saham pada Pareto untuk melihat detail.'}
function bindRows(){document.querySelectorAll('tr[data-ticker]').forEach(e=>e.onclick=()=>detail(e.dataset.ticker))}
function detail(t){const s=data.find(x=>x.ticker===t);if(!s)return;const a=StockFlow.analyze(s.rows,+$('lookback').value),b=a.broker||{};$('detail').innerHTML=`<div class="detailgrid"><div><small>Signal</small><b>${a.signal}</b></div><div><small>Score</small><b>${fmt(a.score,0)}</b></div><div><small>Confidence</small><b>${fmt(a.confidence,0)}</b></div><div><small>Pattern</small><b>${esc(a.pattern)}</b></div><div><small>Accumulation</small><b>${fmt(a.acc,0)}</b></div><div><small>Distribution</small><b>${fmt(a.dist,0)}</b></div><div><small>Broker flow</small><b>${fmt(a.brokerScore,0)}</b></div><div><small>Flow status</small><b>${b.available?'ACTIVE':'NOT AVAILABLE'}</b></div><div><small>Broker persistence 5D</small><b>${fmt(b.persistence5,0)}</b></div><div><small>Concentration</small><b>${fmt(b.concentration,0)}</b></div><div><small>Flow divergence</small><b>${fmt(b.divergence,0)}</b></div><div><small>Rotation</small><b>${fmt(b.rotation,0)}</b></div><div><small>Breakdown risk</small><b>${fmt(a.breakdown,0)}</b></div><div><small>Support</small><b>${fmt(a.support,0)}</b></div><div><small>Resistance</small><b>${fmt(a.resistance,0)}</b></div></div>`}
function refresh(){const old=new Set(selectedTickers);if(!selectedTickers.size||selectedTickers.size>data.length)selectedTickers=new Set(data.map(x=>x.ticker));const el=$('stockChecklist');el.innerHTML=`<label class="checkall"><input type="checkbox" id="checkAll" ${selectedTickers.size===data.length?'checked':''}> ALL</label>`+data.map(x=>`<label><input type="checkbox" value="${esc(x.ticker)}" ${selectedTickers.has(x.ticker)?'checked':''}> ${esc(x.ticker)}</label>`).join('');el.querySelector('#checkAll').onchange=e=>{selectedTickers=e.target.checked?new Set(data.map(x=>x.ticker)):new Set();refresh();render()};el.querySelectorAll('input:not(#checkAll)').forEach(e=>e.onchange=()=>{if(e.checked)selectedTickers.add(e.value);else selectedTickers.delete(e.value);refresh();render()})}
function ymd(d){return d.toISOString().slice(0,10).replaceAll('-','')}function provider(){return $('provider').value}
function info(){const p=provider();$('providerInfo').textContent=p==='idx'?'IDX direct: sumber resmi IDX. Jika 403, data tidak dipalsukan.':p==='yahoo'?'Yahoo Finance: sumber pihak ketiga; historical/delayed OHLCV, bukan IDX dan bukan realtime exchange feed.':p==='indexalpha'?'Index Alpha: API pihak ketiga; broker/OHLCV sesuai akses akun.':p==='remote-csv'?'Daily Remote CSV: CSV publik pihak ketiga, IDX-derived via imq21; bukan API resmi IDX.':'AUTO: Daily Remote CSV (IDX-derived via imq21) → Yahoo Finance historical → cache lokal. IDX direct hanya opsional; tidak perlu upload CSV.';try{localStorage.setItem(PROVIDER_KEY,p)}catch{}}
function saveCache(){try{localStorage.setItem(CACHE_KEY,JSON.stringify({at:Date.now(),data}))}catch(e){console.warn('[CACHE] save failed',e)}}
function restoreCache(){try{const x=JSON.parse(localStorage.getItem(CACHE_KEY)||'null');if(x?.data?.length){data=x.data;refresh();render();$('status').textContent='OFFLINE CACHE';setLiveStatus(`Cache lokal · ${data.length} saham · bukan data live`);stamp();return true}}catch(e){console.warn('[CACHE] restore failed',e)}return false}
async function loadLiveAll(){const p=provider(),to=new Date(),from=new Date(to.getTime()-89*86400000),label=p==='auto'?'Daily Remote CSV → Yahoo → Cache':p.toUpperCase();setLiveStatus(`Mengambil ALL via ${label}...`);const url=`${BACKEND_URL}/market-range?from=${ymd(from)}&to=${ymd(to)}&provider=${encodeURIComponent(p)}`,res=await fetch(url,{cache:'no-store'}),j=await res.json();if(!res.ok||!j.ok)throw Error(j.error||`HTTP ${res.status}`);const prices=StockFlowProvider.normalize(j.data||[]);if(!prices.length)throw Error('Data market kosong');data=StockFlowProvider.group(prices);brokerRows=[];refresh();render();$('status').textContent=(j.provider||p).toUpperCase();setLiveStatus(`${j.source||p} · ALL · ${data.length} saham · ${prices.length} baris OHLCV · tanpa broker detail`);saveCache();stamp()}
async function loadLiveStock(){const t=[...selectedTickers];if(t.length!==1)return loadLiveAll();const ticker=t[0];const p=provider(),to=new Date(),from=new Date(to.getTime()-89*86400000),url=`${BACKEND_URL}/stock?ticker=${encodeURIComponent(ticker)}&from=${ymd(from)}&to=${ymd(to)}&provider=${encodeURIComponent(p)}`;setLiveStatus(`Mengambil ${ticker} via ${p.toUpperCase()}...`);const res=await fetch(url,{cache:'no-store'}),j=await res.json();if(!res.ok||!j.ok)throw Error(j.error||`HTTP ${res.status}`);const prices=StockFlowProvider.normalize(j.prices||[]),br=j.broker||[];if(!prices.length)throw Error('OHLCV kosong');data=StockFlowProvider.group(StockFlowProvider.mergeBrokerRows(prices,br));brokerRows=br;refresh();selectedTickers=new Set([ticker]);refresh();render();$('status').textContent=(j.provider||p).toUpperCase();setLiveStatus(`${j.source||p} · ${ticker} · ${prices.length} hari · ${br.length} broker rows`);saveCache();stamp()}
function stamp(){$('lastUpdate').textContent=new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}function setLiveStatus(x){$('liveStatus').textContent=x}
async function toggle(){if(liveEnabled){liveEnabled=false;$('liveToggle').textContent='LIVE OFF';setLiveStatus('Live dihentikan');return}try{liveEnabled=true;$('liveToggle').textContent='LIVE ON';await loadLiveStock()}catch(e){liveEnabled=false;$('liveToggle').textContent='LIVE OFF';if(provider()==='auto'&&restoreCache())return;$('status').textContent='OFFLINE';setLiveStatus(`Live gagal: ${e.message} · tidak ada cache lokal`)}}
$('lookback').onchange=render;$('provider').onchange=()=>{info();if(liveEnabled)loadLiveStock().catch(e=>setLiveStatus('Live gagal: '+e.message))};$('liveToggle').onclick=toggle;
try{const s=localStorage.getItem(PROVIDER_KEY);if(['auto','idx','yahoo','indexalpha','remote-csv'].includes(s))$('provider').value=s}catch{}info();refresh();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});